// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHjiw6SvUgKgRnzK7qMcnJ81441-a2IQ8',
    appId: '1:972820353535:web:73aad24ea51aa4938817ca',
    messagingSenderId: '972820353535',
    projectId: 'enova-2083',
    authDomain: 'enova-2083.firebaseapp.com',
    storageBucket: 'enova-2083.firebasestorage.app',
    measurementId: 'G-08RX3DH7WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYzuxXW-MVUzfcpM7Fsk38mmKiX8jpIyo',
    appId: '1:972820353535:android:7de174157ef20c308817ca',
    messagingSenderId: '972820353535',
    projectId: 'enova-2083',
    storageBucket: 'enova-2083.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB_7Al6MCYswwt72lVYXg-owEDVWfv8KY',
    appId: '1:972820353535:ios:6c9a3562b32f643c8817ca',
    messagingSenderId: '972820353535',
    projectId: 'enova-2083',
    storageBucket: 'enova-2083.firebasestorage.app',
    iosClientId: '972820353535-1rim6c3ujgee80s1phlsrsj8rppm6e65.apps.googleusercontent.com',
    iosBundleId: 'com.example.eNova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB_7Al6MCYswwt72lVYXg-owEDVWfv8KY',
    appId: '1:972820353535:ios:6c9a3562b32f643c8817ca',
    messagingSenderId: '972820353535',
    projectId: 'enova-2083',
    storageBucket: 'enova-2083.firebasestorage.app',
    iosClientId: '972820353535-1rim6c3ujgee80s1phlsrsj8rppm6e65.apps.googleusercontent.com',
    iosBundleId: 'com.example.eNova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHjiw6SvUgKgRnzK7qMcnJ81441-a2IQ8',
    appId: '1:972820353535:web:328313be83654e558817ca',
    messagingSenderId: '972820353535',
    projectId: 'enova-2083',
    authDomain: 'enova-2083.firebaseapp.com',
    storageBucket: 'enova-2083.firebasestorage.app',
    measurementId: 'G-ZE73PEQL4R',
  );
}
